#server:
#  port: 8881
#  servlet:
#    context-path: /calculate

#spring:
#  #配置文件
#  profiles:
#    active: dev
#  #热部署
#  devtools:
#    restart:
#      enabled: true

#mybatis:
#  type-aliases-package: com.pbh.calculate.entity
#  mapper-locations: classpath:mapper/*.xml
#
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql