server:
  port: 8880
  servlet:
    context-path: /health-collect

spring:
  #配置文件
  profiles:
    active: dev
  #热部署
  devtools:
    restart:
      enabled: true

mybatis:
  type-aliases-package: com.pbh.collect.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql # 指定数据库类型
  reasonable: true
  params: count=countSql
  support-methods-arguments: true

