server:
  port: 8881
  servlet:
    context-path: /health-calculate

spring:
  #配置文件
  profiles:
    active: dev
  #热部署
  devtools:
    restart:
      enabled: true

mybatis:
  type-aliases-package: com.pbh.collect.entity
  mapper-locations: classpath:mapper/*.xml